version: 0.2

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      # - npm run test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
      #
      export WEBSITE_S3_PREFIX="https://product-catalog-us-west-2-960001015395-static-assets.s3-us-west-2.amazonaws.com/static/"
      sed -i -e "s|/static/|$WEBSITE_S3_PREFIX|g" public/index.html
      # 
      - aws s3 cp --recursive public/ s3://$STATIC_ASSETS_BUCKET/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - packaged.yaml
  discard-paths: yes



