AWSTemplateFormatVersion: 2010-09-09
Description: >-
  cunaguaro product cataloge

Transform:
- AWS::Serverless-2016-10-31

Resources:
  EmailQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join
      - '-'
      - - product
        - catalog
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - emailqueue
  getHomePage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-home-page.getHomePageHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  generatePDF:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/generate-pdf.generatePDF
      Runtime: nodejs12.x
      Timeout: 20
      Environment:
        Variables:
          WEBSITE_S3_BUCKET: !Join
          - '-'
          - - cunaguaro
            - product-catalogue
            - !Ref 'AWS::Region'
            - !Ref 'AWS::AccountId'
            - pdf
            - files
          EMAIL_SQS: !Sub EmailQueue
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /generate-pdf
            Method: post
